[package]
name = "Ship_Sim"
version = "0.1.0"
edition = "2021"



# ====================================================================================================
# Binaries for execution with:
# $ cargo run --bin <name> 
[[bin]]
name = "sim_interface"
path = "src/sim_interface.rs"

[[bin]]
name = "external_force_sim"
path = "src/external_force_sim.rs"

[[bin]]
name = "ship_sim"
path = "src/ship_sim.rs"
# ====================================================================================================



# ====================================================================================================
# Custom made libraries
[lib]
name = "ship_sim_lib"
path = "src/ship_sim_lib/ship_sim_lib.rs"
# ====================================================================================================



[dependencies]
# Crates for generating noise
rand = "0.8" # Random number generator
rand_distr = "0.4"

# Crate for GUI design
eframe = "0.27"
egui_plot = "0.27"

# Crate for linear algebra
nalgebra = { version = "0.32", features = ["serde-serialize"] }

# Used for data structure formatting
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# Crate for multicast communication
socket2 = { version = "0.5", features = ["all"] }


