[interface]
fps = 60.0 # Hz

[ship]
mass = 10000.0 # [kg]
length = 30.0 # [m]
radius = 10.0 # [m]
dimensions = [10.0, 30.0] # (radius, length) [m]
velocity_linear_max = 10.00 # Maximum linear speed the ship can reach [m/s]
velocity_angular_max = 0.15  # Maximum angular speed the ship can reach [rad/s]
simulation_frequency = 100.00 # Hz


