# Set the maximum line width before wrapping
max_width = 5000

# Use spaces instead of tabs
hard_tabs = false

# Allow function calls and struct literals to remain on one line when possible
fn_call_width = 1000
struct_lit_width = 1000
chain_width = 1000
